-- DrinkLab 95 Academy — base de dados de inscrições
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  program text not null,
  nome text not null,
  telefone text not null,
  email text,
  curso text,
  horario text not null,
  frequencia text not null default '3 vezes por semana',
  dias text not null,
  obs text,
  estado text not null default 'Nova'
);

alter table public.registrations enable row level security;

-- O site público pode criar inscrições.
create policy "public can insert registrations"
on public.registrations for insert
to anon, authenticated
with check (true);

-- O painel Admin, nesta versão simples, consulta as inscrições através da publishable key.
create policy "public can read registrations"
on public.registrations for select
to anon, authenticated
using (true);

create policy "public can update registration status"
on public.registrations for update
to anon, authenticated
using (true)
with check (true);

create index if not exists registrations_created_at_idx on public.registrations(created_at desc);
