-- DrinkLab 95 Academy — base de dados
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  program text not null,
  nome text not null,
  telefone text not null,
  email text,
  curso text,
  horario text not null,
  frequencia text not null default '3 vezes por semana',
  dias text not null,
  obs text,
  estado text not null default 'Nova',
  formador_id bigint
);

create table if not exists public.trainers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  email text not null unique,
  acesso_codigo text not null unique,
  categorias text[] not null default '{}',
  ativo boolean not null default true
);

alter table public.registrations enable row level security;
alter table public.trainers enable row level security;

-- Inscrições públicas
create policy "public can insert registrations" on public.registrations for insert to anon, authenticated with check (true);
create policy "public can read registrations" on public.registrations for select to anon, authenticated using (true);
create policy "public can update registration status" on public.registrations for update to anon, authenticated using (true) with check (true);

-- Formadores: o Admin pode gerir pela aplicação atual.
create policy "public can read trainers" on public.trainers for select to anon, authenticated using (true);
create policy "public can insert trainers" on public.trainers for insert to anon, authenticated with check (true);
create policy "public can update trainers" on public.trainers for update to anon, authenticated using (true) with check (true);
create policy "public can delete trainers" on public.trainers for delete to anon, authenticated using (true);

-- Associação opcional aluno -> formador
alter table public.registrations drop constraint if exists registrations_formador_id_fkey;
alter table public.registrations add constraint registrations_formador_id_fkey foreign key (formador_id) references public.trainers(id) on delete set null;

create index if not exists registrations_created_at_idx on public.registrations(created_at desc);
create index if not exists registrations_formador_id_idx on public.registrations(formador_id);
